BRANDS = [
    ("Crocs", "crocs", "USA"),
    ("Coach", "coach", "USA"),
    ("Karl Lagerfeld", "karl-lagerfeld", "France"),
    ("Polo Ralph Lauren", "polo-ralph-lauren", "USA"),
    ("Nike", "nike", "USA"),
    ("Adidas", "adidas", "Germany"),
    ("Zara", "zara", "Spain"),
    ("Tommy Hilfiger", "tommy-hilfiger", "USA"),
    ("Acne Studios", "acne-studios", "Sweden"),
    ("Lacoste", "lacoste", "France"),
    ("Love Moschino", "love-moschino", "Italy"),
    ("Skims", "skims", "USA"),
    ("Alo", "alo", "USA"),
    ("COS", "cos", "Sweden"),
    ("BOSS", "boss", "Germany"),
    ("Armani", "armani", "Italy"),
    ("Max Mara", "max-mara", "Italy"),
    ("Miu Miu", "miu-miu", "Italy"),
    ("Massimo Dutti", "massimo-dutti", "Spain"),
    ("Tory Burch", "tory-burch", "USA"),
    ("On Running", "on-running", "Switzerland"),
    ("Pinko", "pinko", "Italy"),
    ("Tom Ford", "tom-ford", "USA"),
    ("Michael Kors", "michael-kors", "USA"),
    ("Birkenstock", "birkenstock", "Germany"),
    ("UGG", "ugg", "USA"),
    ("Premiata", "premiata", "Italy"),
    ("Ralph Lauren", "ralph-lauren", "USA"),
    ("Moon Boot", "moon-boot", "Italy"),
    ("Katy Perry", "katy-perry", "USA"),
    ("Calvin Klein", "calvin-klein", "USA"),
    ("New Balance", "new-balance", "USA"),
    ("Bimba y Lola", "bimba-y-lola", "Spain"),
    ("Saint Laurent", "saint-laurent", "France"),
    ("Ray-Ban", "ray-ban", "Italy"),
    ("Longchamp", "longchamp", "France"),
    ("Marc Jacobs", "marc-jacobs", "USA"),
    ("Converse", "converse", "USA"),
    ("Burberry", "burberry", "UK"),
    ("Golden Goose", "golden-goose", "Italy"),
    ("Hunter", "hunter", "UK"),
    ("Ami Paris", "ami-paris", "France"),
    ("JW PEI", "jw-pei", "China"),
    ("Lululemon", "lululemon", "Canada"),
    ("Off-White", "off-white", "Italy"),
    ("Steve Madden", "steve-madden", "USA"),
    ("GANT", "gant", "Sweden"),
    ("Mango", "mango", "Spain"),
    ("Vivienne Westwood", "vivienne-westwood", "UK"),
    ("DKNY", "dkny", "USA"),
    ("Elisabetta Franchi", "elisabetta-franchi", "Italy"),
    ("Maison Margiela", "maison-margiela", "Italy"),
    ("Levi's", "levis", "USA"),
    ("Toteme", "toteme", "Sweden"),
    ("Mulberry", "mulberry", "UK"),
    ("Без бренду", "unbranded", ""),
]

CATEGORIES = [
    {
        "name": "Sneakers",
        "slug": "sneakers",
        "sort_order": 1,
        "show_on_home": True,
        "home_layout": "big",
        "home_variant": "dark",
        "home_tag": "Featured",
        "is_featured": True,
    },
    {
        "name": "Outerwear",
        "slug": "outerwear",
        "sort_order": 2,
        "show_on_home": True,
        "home_layout": "wide",
    },
    {
        "name": "Knitwear",
        "slug": "knitwear",
        "sort_order": 3,
        "show_on_home": True,
    },
    {
        "name": "Denim",
        "slug": "denim",
        "sort_order": 4,
        "show_on_home": True,
    },
    {
        "name": "Accessories",
        "slug": "accessories",
        "sort_order": 5,
        "show_on_home": True,
        "home_layout": "wide",
    },
    {
        "name": "Loungewear",
        "slug": "loungewear",
        "sort_order": 6,
        "show_on_home": True,
        "home_tag": "New",
    },
    {
        "name": "Bags",
        "slug": "bags",
        "sort_order": 7,
        "show_on_home": False,
    },
    {
        "name": "Footwear",
        "slug": "footwear",
        "sort_order": 8,
        "show_on_home": False,
    },
    {
        "name": "Dresses",
        "slug": "dresses",
        "sort_order": 9,
        "show_on_home": False,
    },
    {
        "name": "Tops",
        "slug": "tops",
        "sort_order": 10,
        "show_on_home": False,
    },
]
