# Generated by Django 5.1.15 on 2026-06-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_home_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вкажіть якщо товар зі знижкою. Відображається перекресленою поруч з актуальною ціною.', max_digits=10, null=True, verbose_name='Стара ціна (до знижки)'),
        ),
    ]
