# Generated by Django 5.2.1 on 2026-05-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_main', models.CharField(default='Всі бренди /', max_length=200)),
                ('hero_title_accent', models.CharField(default='всі дропи', max_length=200)),
                ('hero_blurb', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Сторінка каталогу',
                'verbose_name_plural': 'Сторінка каталогу',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_lead', models.TextField(blank=True)),
                ('channels_desc', models.TextField(blank=True)),
                ('form_heading_1', models.CharField(blank=True, max_length=100)),
                ('form_heading_2', models.CharField(blank=True, max_length=100)),
                ('form_heading_accent', models.CharField(blank=True, max_length=100)),
                ('form_aside_body', models.TextField(blank=True)),
                ('faq_heading_main', models.CharField(blank=True, max_length=100)),
                ('faq_heading_accent', models.CharField(blank=True, max_length=100)),
                ('faq_intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Сторінка контактів',
                'verbose_name_plural': 'Сторінка контактів',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_blurb', models.TextField(blank=True)),
                ('editorial_stamp', models.CharField(blank=True, max_length=100)),
                ('editorial_image', models.ImageField(blank=True, null=True, upload_to='pages/home/')),
                ('editorial_eyebrow', models.CharField(blank=True, max_length=100)),
                ('editorial_title_main', models.CharField(blank=True, max_length=100)),
                ('editorial_title_accent', models.CharField(blank=True, max_length=100)),
                ('editorial_body_1', models.TextField(blank=True)),
                ('editorial_body_2', models.TextField(blank=True)),
                ('newsletter_heading_1', models.CharField(blank=True, max_length=100)),
                ('newsletter_heading_2', models.CharField(blank=True, max_length=100)),
                ('newsletter_heading_3', models.CharField(blank=True, max_length=100)),
                ('newsletter_subtext', models.TextField(blank=True)),
                ('newsletter_counter_label', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
                ('return_period_days', models.PositiveSmallIntegerField(default=14)),
                ('pickup_reserve_hours', models.PositiveSmallIntegerField(default=24)),
                ('support_hours', models.CharField(default='09:00 — 23:00, щодня', max_length=100)),
                ('response_time_mins', models.PositiveSmallIntegerField(default=4)),
                ('telegram_support', models.CharField(default='@droproom_support', max_length=50)),
                ('telegram_channel', models.CharField(default='@droproom_drops', max_length=50)),
                ('phone_main', models.CharField(blank=True, max_length=20)),
                ('email_main', models.EmailField(default='hello@droproom.ua', max_length=254)),
                ('email_press', models.EmailField(default='press@droproom.ua', max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('founded_year', models.PositiveSmallIntegerField(default=2019)),
                ('footer_desc', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_1', models.CharField(blank=True, max_length=100)),
                ('hero_title_2', models.CharField(blank=True, max_length=100)),
                ('hero_title_accent', models.CharField(blank=True, max_length=100)),
                ('hero_lead', models.TextField(blank=True)),
                ('pillars_heading', models.CharField(blank=True, max_length=200)),
                ('timeline_heading_main', models.CharField(blank=True, max_length=100)),
                ('timeline_heading_2', models.CharField(blank=True, max_length=100)),
                ('timeline_heading_accent', models.CharField(blank=True, max_length=100)),
                ('timeline_intro', models.TextField(blank=True)),
                ('quote_text', models.TextField(blank=True)),
                ('quote_author', models.CharField(blank=True, max_length=200)),
                ('cta_heading_1', models.CharField(blank=True, max_length=100)),
                ('cta_heading_2', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Сторінка про нас',
                'verbose_name_plural': 'Сторінка про нас',
            },
        ),
        migrations.CreateModel(
            name='UtilityBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Рядок анонсу',
                'verbose_name_plural': 'Рядки анонсів',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='pages.contactspage')),
            ],
            options={
                'verbose_name': "Канал зв'язку",
                'verbose_name_plural': "Канали зв'язку",
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='pages.contactspage')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_blocks', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Блок статистики',
                'verbose_name_plural': 'Блоки статистики',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('hours', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('telegram', models.CharField(blank=True, max_length=50)),
                ('pickup_eta', models.CharField(blank=True, max_length=50)),
                ('maps_url', models.URLField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='pages.contactspage')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазини',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StoryPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title_line1', models.CharField(max_length=100)),
                ('title_line2', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='pages.storypage')),
            ],
            options={
                'verbose_name': 'Принцип',
                'verbose_name_plural': 'Принципи',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StoryTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('is_accent_year', models.BooleanField(default=False)),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('drop_tag', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='pages.storypage')),
            ],
            options={
                'verbose_name': 'Подія хронології',
                'verbose_name_plural': 'Хронологія',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pages/team/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='pages.storypage')),
            ],
            options={
                'verbose_name': 'Член команди',
                'verbose_name_plural': 'Команда',
                'ordering': ['sort_order'],
            },
        ),
    ]
