# Generated by Django 5.2.1 on 2026-05-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroStripCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('category', 'Категорія (світла)'), ('drop', 'Дроп (темна, по центру)')], default='category', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Фото для фону картки. Без файлу — нейтральний фон.', null=True, upload_to='pages/home/hero/')),
                ('label', models.CharField(blank=True, help_text='Плашка зверху, напр. FIGURE · COAT · STUDIO', max_length=120)),
                ('title', models.CharField(help_text='Заголовок внизу. Перенос рядка: Outerwear /<br>Spring Layers', max_length=200)),
                ('meta', models.CharField(blank=True, help_text='Статистика справа внизу. Два рядки через Enter.', max_length=200)),
                ('link', models.CharField(blank=True, help_text='Посилання, напр. /catalog/?category=sneakers або порожньо', max_length=255)),
                ('use_live_drop', models.BooleanField(default=True, help_text='Для типу «Дроп»: номер і дата з актуального Drop у каталозі.')),
                ('drop_label', models.CharField(blank=True, default='— Drop No.', max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_cards', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Картка hero',
                'verbose_name_plural': 'Картки hero (під заголовком)',
                'ordering': ['sort_order'],
            },
        ),
    ]
