# Generated by Django 5.1.15 on 2026-07-10 12:48

import re

import django.core.validators
from django.db import migrations, models


def migrate_hero_card_labels(apps, schema_editor):
    HeroStripCard = apps.get_model("pages", "HeroStripCard")
    for card in HeroStripCard.objects.all():
        if card.label:
            continue
        title = (card.title or "").strip()
        if not title:
            continue
        label = re.sub(r"<[^>]+>", " ", title)
        label = re.sub(r"\s+", " ", label).strip()
        if label:
            card.label = label[:120]
            card.save(update_fields=["label"])


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_seed_hero_cards"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="herostripcard",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Слайд hero",
                "verbose_name_plural": "Слайди hero",
            },
        ),
        migrations.AddField(
            model_name="herostripcard",
            name="cta_text",
            field=models.CharField(
                default="Переглянути",
                help_text="Кнопка справа внизу на слайді.",
                max_length=60,
                verbose_name="Текст кнопки",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_slider_autoplay_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Увімкнути автоматичне гортання слайдів.",
                verbose_name="Автопрокрут",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_slider_autoplay_seconds",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Затримка між слайдами, від 2 до 60 секунд.",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="Інтервал автопрокруту (сек)",
            ),
        ),
        migrations.RunPython(migrate_hero_card_labels, migrations.RunPython.noop),
        migrations.RemoveField(model_name="herostripcard", name="drop_label"),
        migrations.RemoveField(model_name="herostripcard", name="layout"),
        migrations.RemoveField(model_name="herostripcard", name="meta"),
        migrations.RemoveField(model_name="herostripcard", name="title"),
        migrations.RemoveField(model_name="herostripcard", name="use_live_drop"),
        migrations.AlterField(
            model_name="herostripcard",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Фото слайда. Рекомендовано 1800×760 px або ширше.",
                null=True,
                upload_to="pages/home/hero/",
            ),
        ),
        migrations.AlterField(
            model_name="herostripcard",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="herostripcard",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Підпис зліва внизу, напр. Footwear або Jacquemus.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="herostripcard",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Посилання при кліку, напр. /catalog/?category=sneakers. Порожньо — каталог.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="herostripcard",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
