# Generated by Django 5.1.15 on 2026-07-10 12:57

from django.db import migrations, models


def migrate_hero_cards_to_m2m(apps, schema_editor):
    HomePage = apps.get_model("pages", "HomePage")
    HeroStripCard = apps.get_model("pages", "HeroStripCard")
    HeroSlideImage = apps.get_model("pages", "HeroSlideImage")

    home, _ = HomePage.objects.get_or_create(pk=1)
    order = 0

    for card in HeroStripCard.objects.filter(is_active=True).order_by("sort_order", "pk"):
        if not card.image:
            continue
        slide = HeroSlideImage.objects.create(image=card.image, sort_order=order)
        home.hero_slide_images.add(slide)
        order += 1


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_hero_slider_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Рекомендовано 1800×760 px, landscape.",
                        upload_to="pages/home/hero/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Фото hero",
                "verbose_name_plural": "Фото hero",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_slide_images",
            field=models.ManyToManyField(
                blank=True,
                related_name="home_pages",
                to="pages.heroslideimage",
                verbose_name="Фото слайдера",
            ),
        ),
        migrations.RunPython(migrate_hero_cards_to_m2m, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="HeroStripCard",
        ),
    ]
