# Generated by Django 5.1.15 on 2026-07-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_hero_slide_inline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslideimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = автоматично в кінець списку.', verbose_name='Порядок'),
        ),
    ]
