# Generated by Django 5.1.15 on 2026-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_hero_slide_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslideimage',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'Слайд hero', 'verbose_name_plural': 'Слайди hero'},
        ),
        migrations.AddField(
            model_name='heroslideimage',
            name='panel_theme',
            field=models.CharField(choices=[('light', 'Світла (стандартна)'), ('dark', 'Темна (акцентний воордмарк)')], default='light', help_text='Світла — стандартна панель зі слоганом. Темна — темний фон, білий воордмарк-заголовок без CAPS.', max_length=10, verbose_name='Тема панелі'),
        ),
    ]
