# Generated by Django 5.1.15 on 2026-07-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_compare_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(unique=True, verbose_name='ID каналу')),
                ('last_message_id', models.BigIntegerField(default=0, verbose_name='Останній message_id')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Остання синхронізація')),
            ],
            options={
                'verbose_name': 'Стан синхронізації Telegram',
                'verbose_name_plural': 'Стани синхронізації Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(verbose_name='ID каналу')),
                ('message_id', models.BigIntegerField(verbose_name='message_id')),
                ('media_group_id', models.CharField(blank=True, max_length=64, verbose_name='ID медіа-групи')),
                ('raw_caption', models.TextField(blank=True, verbose_name='Текст поста')),
                ('photo_file_ids', models.JSONField(blank=True, default=list, verbose_name='Telegram file_id фото')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('imported', 'Імпортовано'), ('failed', 'Помилка'), ('skipped', 'Пропущено')], default='pending', max_length=20, verbose_name='Статус')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Імпортовано о')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_imports', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Імпорт з Telegram',
                'verbose_name_plural': 'Імпорти з Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel_id', 'media_group_id'], name='telegram_im_channel_3285b1_idx'), models.Index(fields=['status'], name='telegram_im_status_b42d31_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel_id', 'message_id'), name='telegram_import_unique_message')],
            },
        ),
    ]
