# Generated by Django 5.2.1 on 2026-05-20 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Підписник',
                'verbose_name_plural': 'Підписники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DropNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='catalog.drop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Нагадування про дроп',
                'verbose_name_plural': 'Нагадування про дропи',
                'ordering': ['-created_at'],
                'unique_together': {('drop', 'email')},
            },
        ),
    ]
